import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/Components/layout/Header";
import Footer from "@/Components/layout/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700"],
});

export const metadata = {
  title: "BiteBuddy || Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <Header></Header>
        <div className="max-w-5xl mx-auto">
        </div>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
